---
abstract: 'Dispatch actions based on HTTP request methods'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
generated_by: 'Dist::Zilla version 1.093000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-ActionRole-MatchRequestMethod
requires:
  Catalyst::Controller::ActionRole: 0
  Catalyst::Runtime: 0
  HTTP::Request::Common: 0
  Moose::Role: 0
  Perl6::Junction: 0
  Test::More: 0.89
  namespace::autoclean: 0
version: 0.01
